name: PROD Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---------- LOGIN GHCR ----------
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # ---------- API BUILD ----------
      - name: Build API image
        run: |
          docker build \
            -f docker/api.Dockerfile \
            -t ghcr.io/${{ github.repository }}-api:latest .

      - name: Push API
        run: docker push ghcr.io/${{ github.repository }}-api:latest

      # ---------- WEB BUILD ----------
      - name: Build Web image
        run: |
          docker build \
            -f docker/web.Dockerfile \
            -t ghcr.io/${{ github.repository }}-web:latest .

      - name: Push Web
        run: docker push ghcr.io/${{ github.repository }}-web:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd /home/dan/app

            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_TOKEN }}

            docker compose pull
            docker compose up -d
