name: PROD Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set image base name
        run: echo "IMAGE_BASE=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # ---------- x86 ----------
      # - name: Build API image
      #   run: |
      #     docker build \
      #       -f docker/api.Dockerfile \
      #       -t $IMAGE_BASE-api:latest .

      # - name: Push API
      #   run: docker push $IMAGE_BASE-api:latest
      # - name: Build Web image
      #   run: |
      #     docker build \
      #       -f docker/web.Dockerfile \
      #       -t $IMAGE_BASE-web:latest .

      # - name: Push Web
      #   run: docker push $IMAGE_BASE-web:latest

      # ---------- ARM ----------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push API
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/api.Dockerfile
          push: true
          platforms: linux/arm64
          tags: ${{ env.IMAGE_BASE }}-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/web.Dockerfile
          push: true
          platforms: linux/arm64
          tags: ${{ env.IMAGE_BASE }}-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Debug workspace
        run: |
          pwd
          ls -R

      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          source: "./docker/docker-compose.yml"
          target: "/home/dan/app/docker-compose.yml"

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd /home/dan/app

            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_TOKEN }}

            docker compose pull
            docker compose up -d
